### ISSUE TITLE
django-compress contains GPL'd code.

### ISSUE THREAD

**Issue by mintchaos** [pelme/django-compress#1]
The csstidy_python bits included with django-compress are GPL. 
It's not obvious at all that GPL code is included. This puts anyone who uses django-compress in danger of violating the GPL without realizing it. Kinda freaked me out when I saw it.

This also puts django-compress itself in danger of violating the GPL since it is not licensed under GPL. 

The easiest way to deal with this is to remove the csstidy_python filter from the project and put it in it's own GPL'd repo. so people can use it alongside django-compress if they want. But they'll know they are entering GPL land explicitly.

http://github.com/pelme/django-compress/blob/6f400b9f26fde8308345099287f213826805d1e7/compress/filters/csstidy_python/csstidy.py

**Comment by pelme** [comment]
As you might have noticed, django-compress has not been updated in a long time.

I will not continue to maintain it in the future, I suggest you check out cyberdelias django-pipeline fork instead!

Therefore, I will keep everything as-is, and I encourage everyone to switch to django-pipeline which does not contain this code.

Sorry for the inconvenience!
