### ISSUE TITLE
django-compress code all over the place

### ISSUE THREAD

**Issue by adamn** [pelme/django-compress#3]
The source code and wiki pages needs to be cleaned up for django-compress.  For the newcomer, it's impossible to tell what's going on.  I propose:
1. Ask each of the fork maintainers to either make their fork ready for pulling back into the repository (Whichever that one is) or delete their fork or just let people know that their fork is just for experimentation and not for public use.  http://github.com/Amli/django-compress/network
2. Move all the documentation from Google code to here.
3. Put a link on Google code directing users to the correct Github repository.
4. Straighten out the multiple django-compress projects on PyPI and put the best one up there.

Cheers.

**Comment by vilcans** [comment]
+1. Is this project abandoned by the original author? Is there an official "latest" version? Total confusion here.

**Comment by cyberdelia** [comment]
This project is mostly abandoned by the original author, I've been maintaining a working, up to date fork and trying to get it merge with no success. You can find my fork here if you're interrested : https://github.com/cyberdelia/django-pipeline

**Comment by pelme** [comment]
django-compress has not been maintained properly, and all the forks are a bit of a problem. My suggestion is that we encourage everyone to switch to django-pipeline, and make that the "official branch". Getting all the forks merged seems like a huge task, and django-pipeline seems to have come a long way already.

To answer your points:
1. I will update the README to point out that this project is not maintained any more, and that people should consider switching to django-pipeline.
2. I have added a fat disclaimer on all the Google Code wiki pages, I think thats more helpful than just removing them.
3. See above.
4. See above, I suggest we encourage everyone to use django-pipeline.

Let me know if I can be of any help to get people to use django-pipeline instead!
