### ISSUE TITLE
Running synccompress with a source that has only external URLs causes KeyError

### ISSUE THREAD

**Issue by cgreene** [pelme/django-compress#5]
For a source with only external urls, synccompress raises a keyerror here:
u, version = needs_update(js['output_filename'],
    js['source_filenames'])

Wrapping with try/except fixes this
try:
    u, version = needs_update(js['output_filename'],
        js['source_filenames'])
except KeyError:
    print('JavaScript Group \'%s\' could not be compressed (does it only have external URLs?)' % name)
    continue

**Comment by pelme** [comment]
As you might have noticed, django-compress has not been updated in a long time.

I will not continue to maintain it in the future, I suggest you check out cyberdelias django-pipeline fork instead!

Switching to django-pipeline will likely solve your problems, if not, please file issues there instead.

Sorry for the inconvenience!
